### PR TITLE
fix(express&router methods): accept arrays as callbacks

### PR DESCRIPTION
**Pull request by racer01**
Express methods can accept array of middlewares as callbacks, while this throws an error.

**What**:
Fixed express and router methods so they accept all kind of callbacks accepted by Express.

**Why**:
Express method callbacks can be 
- A middleware function.
- A series of middleware functions (separated by commas).
- An array of middleware functions.
- A combination of all of the above.
as of [Express docs](https://expressjs.com/en/4x/api.html#app.get.method).

**How**:
Refactored express.get and router handler to have `callbacks` rest parameter.

### CODE REVIEW

**Comment by racer01** [comment]
I added tests. (Also you were right requesting them, I forgot to flatten rest parameter)

**Comment by jameswlane** [comment]
@racer01 Awesome!
When I get home this afternoon I will merge this in and cut a new release.

👍 You rock! 🎉

**Comment by racer01** [comment]
Thanks, I'm happy to help!

**Pull request merged**
