### PR TITLE
set the response.body when using response write methods

### PR DESCRIPTION
**Pull request by y0y0z**
set the `reponse.body` when using `response.json()`, `response.jsonp()`, `response.text()`

### CODE REVIEW

**Comment by y0y0z** [comment]
@jameswlane: couldn't understand which [issue was introduced](https://codebeat.co/projects/github-com-jameswlane-jest-express-master/pull_requests/321606). would you please shed the light on the issue?

**Comment by jameswlane** [comment]
@y0y0z It’s having a issue due to there are too many lines in the function. We could refactor and group code with some of the same functionality. In the constructor we could have a method to like `setupProperties(this){}`

**Comment by y0y0z** [comment]
@jameswlane: sounds good. meanwhile, what do you think of merging it?

**Pull request merged**
